---
- name: Execute ansible.builtin.shells and Generate HTML Report
  hosts: all
  gather_facts: true
  become: true
  ignore_errors: true
  tasks:
    - name: Execute df ansible.builtin.shell
      ansible.builtin.shell: df -hTP | grep -v tmpfs
      register: df_output

    - name: Execute cat /etc/fstab ansible.builtin.shell
      ansible.builtin.shell: cat /etc/fstab
      register: fstab_output

    - name: Execute route ansible.builtin.shell
      ansible.builtin.shell: route -n
      register: route_output

    - name: Execute uname ansible.builtin.shell
      ansible.builtin.shell: uname -a
      register: uname_output

    - name: Execute pvs ansible.builtin.shell
      ansible.builtin.shell: pvs
      register: pvs_output

    - name: Execute vgs ansible.builtin.shell
      ansible.builtin.shell: vgs
      register: vgs_output

    - name: Execute lvs ansible.builtin.shell
      ansible.builtin.shell: lvs
      register: lvs_output

    - name: Execute lsblk ansible.builtin.shell
      ansible.builtin.shell: lsblk
      register: lsblk_output

    - name: Execute lsblk -f ansible.builtin.shell
      ansible.builtin.shell: lsblk -f
      register: lsblk_f_output

    - name: Execute mount ansible.builtin.shell
      ansible.builtin.shell: mount
      register: mount_output

    - name: Execute cat /etc/resolv.conf ansible.builtin.shell
      ansible.builtin.shell: cat /etc/resolv.conf
      register: resolv_conf_output

    - name: Execute cat /etc/hosts ansible.builtin.shell
      ansible.builtin.shell: cat /etc/hosts
      register: etc_hosts_output

    - name: Execute ip a ansible.builtin.shell
      ansible.builtin.shell: ip a
      register: ip_a_output

    - name: Execute cat /etc/os*release ansible.builtin.shell
      ansible.builtin.shell: cat /etc/os-release
      register: os_release_output

    - name: Execute clustat ansible.builtin.shell
      ansible.builtin.shell: clustat
      register: clustat_output

    - name: Execute pcs status ansible.builtin.shell
      ansible.builtin.shell: pcs status
      register: pcs_status_output

    - name: Execute ps -ef | grep -i pmon ansible.builtin.shell
      ansible.builtin.shell: ps -ef | grep -i pmon
      register: pmon_output

    - name: Execute dmidecode -t1 ansible.builtin.shell
      ansible.builtin.shell: dmidecode -t1
      register: dmidecode_output

    - name: Execute multipath -ll ansible.builtin.shell
      ansible.builtin.shell: multipath -ll
      register: multipath_output

    - name: Execute multipath -ll | grep -i SYMMETRIX | wc -l ansible.builtin.shell
      ansible.builtin.shell: multipath -ll | grep -i SYMMETRIX | wc -l
      register: symmetrix_count_output

    - name: Execute ip a ansible.builtin.shell
      ansible.builtin.shell: ip a
      register: ip_a_output

    - name: Execute cat /proc/net/bonding/bond0 ansible.builtin.shell
      ansible.builtin.shell: cat /proc/net/bonding/bond0
      register: bonding_bond0_output

    - name: Execute cat /proc/net/bonding/bond1 ansible.builtin.shell
      ansible.builtin.shell: cat /proc/net/bonding/bond1
      register: bonding_bond1_output

    - name: Execute cat /proc/net/bonding/bond2 ansible.builtin.shell
      ansible.builtin.shell: cat /proc/net/bonding/bond2
      register: bonding_bond2_output

    - name: Generate HTML Report
      ansible.builtin.template:
        src: report_template.html.j2
        dest: /tmp/generated_report.html
