---
- name: Restoring receptor configuration
  hosts: all
  become: true
  vars:
    env: charlie
  tasks:
    - name: Stop the receptor service
      ansible.builtin.service:
        name: receptor
        state: stopped

    - name: Check if receptor-{{ env }}.tar.gz file exists
      ansible.builtin.stat:
        path: /root/receptor-{{ env }}.tar.gz
      register: receptor_exists

    - name: Find all files in the target directory
      ansible.builtin.find:
        paths: /etc/receptor
        recurse: yes
        file_type: file
      register: files_to_delete

    - name: Delete each file in the receptor directory
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"
      when: receptor_exists.stat.exists

    # using builtin instead of community
    - name: Unarchive receptor-{{ env }}.tar.gz files in /etc/receptor
      ansible.builtin.shell: tar -xvzf /root/receptor-{{ env }}.tar.gz -C /etc/receptor/
      register: unarch
      when: receptor_exists.stat.exists

    - name: Restart the receptor if unarchive is successful
      ansible.builtin.service:
        name: receptor
        state: restarted
      when: unarch.changed
