- name: Echo Inventory Hostname and Create Custom Inventory File
  hosts: all
  gather_facts: false
  tasks:
    - name: Task 1 - Echo Inventory Hostname
      ansible.builtin.debug:
        msg: "Inventory Hostname: {{ inventory_hostname }}"

    - name: Check if custom inventory file exists
      ansible.builtin.stat:
        path: /tmp/custom_inventory.ini
      delegate_to: localhost
      register: file_check

    - name: Create empty custom inventory file if it doesn't exist
      ansible.builtin.file:
        path: /tmp/custom_inventory.ini
        state: touch
      delegate_to: localhost
      when: not file_check.stat.exists

    - name: Create the hosts section
      ansible.builtin.lineinfile:
        path: /tmp/custom_inventory.ini
        line: "[hosts]"
        insertafter: EOF
      delegate_to: localhost

    - name: Add hosts to the inventory file
      ansible.builtin.lineinfile:
        path: /tmp/custom_inventory.ini
        line: "{{ item }} ansible_user=perf"
        insertafter: "[hosts]"
      delegate_to: localhost
      loop: "{{ groups['all'] }}"
          
    - name: cat the output
      ansible.builtin.shell: "cat /tmp/custom_inventory.ini"
      delegate_to: localhost

    - name: pause
      ansible.builtin.pause:
        seconds: 600
