- name: Host healthcheck
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Generate HTML report for each host
      template:
        src: host_details_report.j2
        dest: /tmp/health_check_report.html
      delegate_to: localhost
