---
- name: Generate Host Details HTML Reports
  hosts: all
  gather_facts: true

  tasks:
    - name: Generate HTML report for each host
      template:
        src: host_details_report.j2
        dest: /tmp/health_check_report.html


    - name: copy the file to httpd document root
      copy:
        src: /tmp/health_check_report.html
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        
