---
- name: test kerberos authentication
  hosts: all
  connection: winrm
  gather_facts: false
  serial: 1
  vars:
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: win ping
      win_ping:

    - name: nullify the variable
      set_fact:
        hostname_output: ""
        
    - name: Get Full Hostname
      ansible.builtin.setup:
      register: hostname_output
      
    - name: Display Hostname, CPU, and Memory Info
      debug:
        msg: |
          Hostname: {{ inventory_hostname }}
          CPU Cores: {{ hostname_output.ansible_facts.ansible_processor_cores }}
          Memory Total: {{ hostname_output.ansible_facts.ansible_memtotal_mb }} MB
          Memory Free: {{ hostname_output.ansible_facts.ansible_memfree_mb }} MB

    - name: Check if service is running
      win_service:
        name: "{{ item }}"
        state: started
      with_items:
        - wuauserv
        - BITS
      register: service_status

    - name: Display service status
      debug:
        var: service_status
