---
- hosts: all
  tasks:
    - name: copy ssh key file to the end host
      shell: echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyO7XL5Y5g1eOKQGgxOvOgxgEM4x1HuifL2KBqEHqURAnLrjkavyH5vmz0QeG10iZdagISBgwtujOsSRr+yyagh01G2Gx0OdobokRmFqEHtUaDBuslcV/Ei2x+TIgK21fktr5P3hvd0mThMFoP7jM+9sBDcZN6DqW5mrtaxMHEgVLB6mR1nogfQ6gMlwE7JtDElOaF6pSdohQ5sLwx249jSSBUMaHbIwdYukz5GZ6nalkLxcaBfPORa3Obkj+UUV+3fOCGN+e4nVRC7UXD2+Zs+n6I3drNKBih6WqMhhAd68rED2rM6vFScQU0t/XREYWnvq69t1tBnrfMD3IyASarKm1gUbGH/ElX3iKSPrfpg4/61dxlx7s3DaNUiWRWs0nWYACRvV+l86fIE1TOgKj9AWcVK1ldwUREyBU+C5nev3p2jP89mqfWCH0TuUbcNAv08k781Mkz8DU0RgLN9sYQvQoAzR3yJskK1g6g4NAGT+uBvW1QdrCprowtaNYeR9s=' >> /home/ec2-user/.ssh/authorized_keys
