---
- name: Create and Retrieve SSH Keys
  hosts: all
  become: true

  tasks:
    - name: Generate SSH Key Pair
      community.general.openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/new_key"
        state: present

    - name: Fetch Private Key to Control Machine
      ansible.builtin.fetch:
        src: "{{ ansible_env.HOME }}/.ssh/new_key"
        dest: "{{ playbook_dir }}/new_key"
        flat: yes
