---
- name: Testing playbook
  hosts: [all]
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Attempt SSH Connection
      ansible.builtin.wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22
        timeout: 10
      ignore_errors: true
      register: result

    # Set ip forwarding on in /proc and verify token value with the sysctl command
    - name: port forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
