---
- name: Install nfs-utils and set up NFS mounts
  hosts: all
  become: yes
  vars:
    ansible_user: quickcluster
    directories:
      - /var/lib/pulp
      - /var/lib/pulp/pulpcore_static
  tasks:
    - name: Install nfs-utils
      yum:
        name: nfs-utils
        state: present

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ directories }}"

    - name: Verify if directories are created
      stat:
        path: "{{ item }}"
      loop: "{{ directories }}"
      register: directory_status

    - name: Retry creating directories until all are available
      file:
        path: "{{ item.item }}"
        state: directory
        mode: '0755'
      loop: "{{ create_directory_result.results }}"
      when: not directory_status.results[loop.index0].stat.exists
      retries: 5
      delay: 5

    - name: Add fstab entries
      blockinfile:
        path: /etc/fstab
        block: |
          node-0.ansibledemo.lab.psi.pnq2.redhat.com:/nfs /var/lib/pulp nfs defaults,_netdev,nosharecache 0 0
          node-0.ansibledemo.lab.psi.pnq2.redhat.com:/nfs/pulpcore_static /var/lib/pulp/pulpcore_static nfs defaults,_netdev,nosharecache,context="system_u:object_r:httpd_sys_content_rw_t:s0" 0 0
        state: present
        create: yes

    - name: Force mount of all fstab entries
      command: mount -a