---
- name: Start services on PAH nodes
  hosts: dc-pah
  gather_facts: true
  become: true
  vars:
    ansible_user: 'quickcluster'
  tasks:
    - name: Start services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: no
      loop:
        - pulpcore.service
        - pulpcore-api.service
        - pulpcore-content.service
        - pulpcore-worker@1.service
        - pulpcore-worker@2.service
        - nginx.service
        - redis.service
      ignore_errors: true
