---
# This playbook checks and cancels spot instances on AWS
- name: Check and Cancel Spot Instances
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  vars:
    region: "ap-south-1" # Define the AWS region here
    ami_name: "rhel" # Define the AMI name here
  tasks:
    # Get information about running instances in the specified region
    - name: Get information about running instances
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          instance-state-name: ["running"]
      register: running_instances

    # Set a fact for running instance IDs if there are any running instances
    - name: Set fact for running instance IDs
      set_fact:
        running_instances_id: "{{ running_instances.instances | map(attribute='instance_id') | join(' ') }}"
      when: running_instances.instances | length > 0

    # Display the running instance IDs if there are any running instances
    - name: Display running instance IDs
      debug:
        var: running_instances_id
      when: running_instances.instances | length > 0

    # Get information about AMIs with the specified name in the specified region
    - name: Get AMI information
      amazon.aws.ec2_ami_info:
        filters:
          "tag:Name": "{{ ami_name }}"
        region: "{{ region }}"
      register: amiss

    # Set a fact for the first AMI ID in the list of AMIs if there are any running instances
    - name: Set fact for AMI ID
      set_fact:
        ami_spot1: "{{ amiss.images[0].image_id }}"
      when: running_instances.instances | length > 0

    # Display the AMI ID if there are any running instances
    - name: Display AMI ID
      debug:
        var: ami_spot1
      when: running_instances.instances | length > 0

    # Deregister the AMI (and delete associated snapshots) if there are any running instances
    - name: Deregister AMI (delete associated snapshots too)
      amazon.aws.ec2_ami:
        state: absent
        region: "{{ region }}"
        image_ids: "{{ ami_spot1 }}"
      when: running_instances.instances | length > 0
