---
- name: Check and Cancel Spot Instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: get the information of running instance
      amazon.aws.ec2_instance_info:
        region: "ap-south-2"
        filters:
          instance-state-name: [ "running"]
      register: running_instances

    - name: Set fact for running instances ID
      set_fact:
        running_instances_id: "{{ running_instances.instances | map(attribute='instance_id') | list }}"
        
    - name: debug the information
      debug:
        msg: "{{ running_instances_id }}"

    - name: create a new ami image
      amazon.aws.ec2_ami:
        instance_id: "{{ running_instances_id }}"
        wait: true
        name: rhel
        tags:
          Name: rhel
          Service: server
