---
- name: Check and Cancel Spot Instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: get the information of running instance
      amazon.aws.ec2_instance_info:
        region: "ap-south-2"
        filters:
          instance-state-name: [ "running"]
      register: running_instances

    - name: Set fact for running instances ID
      set_fact:
        running_instances_id: "{{ running_instances.instances }}"
        
    - name: debug the information
      debug:
        msg: "{{ running_instances_id }}"
