- name: Create AMI from running instances and delete spot instances
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-south-1 # change this to your region
    ami_name: rhel # change this to your desired AMI name
  tasks:
    - name: Find running instances
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          instance-state-name: running
      register: ec2_info

    - name: Find AMI with name rhel
      amazon.aws.ec2_ami_info:
        region: "{{ region }}"
        filters:
          name: "{{ ami_name }}"
      register: ami_info
      when: ec2_info.instances | length > 0 # only run this task if there are running instances

    - name: Delete AMI with name rhel
      amazon.aws.ec2_ami:
        region: "{{ region }}"
        image_id: "{{ item.image_id }}"
        state: absent
        delete_snapshot: yes
      loop: "{{ ami_info.images }}"
      when: ami_info.images | length > 0 # only run this task if there are AMIs with name rhel

    - name: Create AMI from each running instance
      amazon.aws.ec2_ami:
        region: "{{ region }}"
        instance_id: "{{ item.instance_id }}"
        name: "{{ ami_name }}"
        tags:
          Name: rhel
        wait: yes
        delete_snapshot: yes
      loop: "{{ ec2_info.instances }}"
      when: ec2_info.instances | length > 0 # only run this task if there are running instances

    - name: Find spot fleet request ID
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          instance-lifecycle: spot
      register: spot_info
      when: ec2_info.instances | length > 0 # only run this task if there are running instances

    - name: Delete the spot fleet
      amazon.aws.ec2_spot_instance:
        spot_instance_request_ids: ["{{ spot_info.instances[1].spot_instance_request_id }}"]
        state: absent
      when: spot_info.instances | length > 0 # only run this task if there are spot instances
