---
- name: Check and Cancel Spot Instances
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: Get the current date and time
      set_fact:
         current_datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
         
    - name: get the current data and time
      debug:
        msg: "{{ current_datetime }}"
        
    - name: get the information of running instance
      amazon.aws.ec2_instance_info:
        region: "ap-south-1"
        filters:
          instance-state-name: [ "running" ]
      register: running_instances

    - name: Set fact for running instances ID
      set_fact:
        running_instances_id: "{{ running_instances.instances | map(attribute='instance_id') | join(' ') }}"
        
    - name: debug the information
      debug:
        var : running_instances_id
        
    - name: Check the ami ids
      amazon.aws.ec2_ami_info:
        filters:
          "tag:Name": rhel
        region: ap-south-1
      register: amiss

    - name: set the fact for ami
      set_fact:
        ami_spot1: "{{ amiss.images[0].image_id }}"

    - name: debug the ami id
      debug:
        var: ami_spot1

    - name: Deregister AMI (delete associated snapshots too)
      amazon.aws.ec2_ami:
        image_id: "{{ ami_spot1 }}"
        delete_snapshot: True
        state: absent
        region: ap-south-1
      when: running_instances_id | length > 0

    - name: create a new ami image
      amazon.aws.ec2_ami:
        instance_id: "{{ running_instances_id }}"
        region: "ap-south-1"
        wait: true
        name: "rhel"
        tags:
          Name: "rhel"
      when: running_instances_id | length > 0

    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-1"
      register: ami_facts

    - name: Display Active Spot Instance IDs
      debug:
        var: ami_facts

    - name: Extract spot_instance_request_id values
      set_fact:
        spot_instance_request_ids: "{{ ami_facts.spot_request | map(attribute='spot_instance_request_id') | list }}"

    - name: Debug spot_instance_request_ids
      debug:
        var: spot_instance_request_ids
        
    - name: Cancel spot request and terminate instance
      amazon.aws.ec2_spot_instance:
        state: absent
        spot_instance_request_ids: "{{ item }}"
        terminate_instances: yes
        region: ap-south-2
      with_items: "{{ spot_instance_request_ids }}"
      when: running_instances_id | length > 0
