---
- name: Check and Cancel Spot Instances
  hosts: localhost
  gather_facts: false
  ignore_errorsL: true
  tasks:
    - name: get the information of running instance
      amazon.aws.ec2_instance_info:
        region: "ap-south-2"
        filters:
          instance-state-name: [ "running" ]
      register: running_instances

    - name: Set fact for running instances ID
      set_fact:
        running_instances_id: "{{ running_instances.instances | map(attribute='instance_id') | join(' ') }}"
        
    - name: debug the information
      debug:
        var : running_instances_id

    - name: create a new ami image
      amazon.aws.ec2_ami:
        instance_id: "{{ running_instances_id }}"
        region: "ap-south-2"
        wait: true
        name: rhel
        tags:
          Name: rhel
          Service: server

    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Display Active Spot Instance IDs
      debug:
        var: ami_facts

    - name: Extract spot_instance_request_id values
      set_fact:
        spot_instance_request_ids: "{{ ami_facts.spot_request | map(attribute='spot_instance_request_id') | list }}"

    - name: Debug spot_instance_request_ids
      debug:
        var: spot_instance_request_ids
        
    - name: Cancel spot request and terminate instance
      amazon.aws.ec2_spot_instance:
        state: absent
        spot_instance_request_ids: "{{ item }}"
        terminate_instances: yes
        region: ap-south-2
      with_items: "{{ spot_instance_request_ids }}"
