---
- name: Install Jenkins on RHEL 9
  hosts: 	aws_ec2
  become: yes
  vars:
    custom_jenkins_admin_password: 'Redhat@123'
  tasks:
    - name: Install OpenJDK Java
      package:
        name: java-11-openjdk
        state: present

    - name: Add Jenkins YUM repository
      yum_repository:
        name: jenkins
        description: Jenkins Repository
        baseurl: http://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        enabled: yes

    - name: Install Jenkins
      package:
        name: jenkins
        state: latest

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
        
    - name: Wait for Jenkins to be ready
      uri:
        url: http://localhost:8080/login
        method: GET
        return_content: yes
      register: jenkins_response
      until: jenkins_response.content | search("Sign in") is not failed
      retries: 60
      delay: 10

    - name: Update Jenkins admin password
      uri:
        url: http://localhost:8080/scriptText
        method: POST
        body_format: form-urlencoded
        body: "script=import jenkins.model.Jenkins; Jenkins.instance.securityRealm.createAccount('admin', '{{ custom_jenkins_admin_password }}').save()"
        return_content: yes
      register: password_update_response
      until: password_update_response.status == 200
      retries: 5
      delay: 5

    - name: Verify Jenkins admin password update
      uri:
        url: http://localhost:8080/scriptText
        method: POST
        body_format: form-urlencoded
        body: "script=println(hudson.security.HudsonPrivateSecurityRealm.PASSWORD_ENCODER.matches('{{ custom_jenkins_admin_password }}', Jenkins.instance.securityRealm.loadUserByUsername('admin').password))"
        return_content: yes
      register: verify_password_response

    - name: Display password update result
      debug:
        msg: "Jenkins admin password update successful: {{ verify_password_response.content | bool }}"
