---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get AMI images
      amazon.aws.ec2_ami:
        name: "rhel"
        region: "ap-south-2"
      register: ami_result

    - name: Display old AMI images
      debug:
        var: ami_result
