---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Display Active Spot Instance IDs
      debug:
        var: ami_facts

    - name: Set Facts for Active Spot Instance Fleet Request IDs
      set_fact:
        active_spot_instance_request_ids: "{{ ami_facts.spot_request | json_query(query) }}"
      vars:
        query: "[?state == 'active' && tags[?key == 'aws:ec2spot:fleet-request-id']].spot_instance_request_id"
      tags: always

    - name: Display Active Spot Instance Fleet Request IDs
      debug:
        var: active_spot_instance_request_ids
