---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Extract Active Spot Instance Request IDs
      debug:
        var: item.spot_instance_request_id
      loop: "{{ ami_facts.spot_request }}"
      when: item.state == "active"
