---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: List old AMI images
      amazon.ami.ec2_ami:
        filters:
          name:
            - rhel
        image_filter:
          age:
            lt: 6h
        state: list

      - name: Display old AMI images
        debug:
          var: ec2_ami.results
