---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Display Active Spot Instance IDs
      debug:
        var: ami_facts

    - name: Extract Value
      debug:
        var: item.value
      with_items: "{{ ami_facts.spot_request[?tags[0].key == 'aws:ec2spot:fleet-request-id'].tags[0].value }}"
