---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Display Active Spot Instance IDs
      debug:
        var: ami_facts

    - name: Extract spot_instance_request_id values
      set_fact:
        spot_instance_request_ids: "{{ ami_facts.spot_request | map(attribute='spot_instance_request_id') | list }}"

    - name: Debug spot_instance_request_ids
      debug:
        var: spot_instance_request_ids
