---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Display old AMI images
      debug:
        var: ami_facts
