---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get AMI facts
      amazon.aws.ec2_ami_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Display old AMI images
      debug:
        var: ami_facts
