---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: List old AMI images
      amazon.aws.ec2_ami:
        filters:
          name:
            - rhel
        image_filter:
          age:
            lt: 6h
        state: present
      register: ec2_ami

    - name: Display old AMI images
      debug:
        var: ec2_ami.results
