---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: describe the Spot Instance requests based on request IDs
      amazon.aws.ec2_spot_instance_info:
        region: "ap-south-2"
      register: ami_facts

    - name: Extract Active Spot Instance Request IDs
      set_fact:
        active_spot_instance_ids: "{{ active_spot_instance_ids | default([]) + [item.spot_instance_request_id] }}"
      loop: "{{ ami_facts.spot_request }}"
      when: item.state == "active"

    - name: Display Active Spot Instance IDs
      debug:
        var: active_spot_instance_ids
