---
- name: Create Spot Instance with Available AMI
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Search for available AMIs
      ec2_ami_find:
        region: ap-south-1
        owner: self
        architecture: x86_64
        name: "v1.7"  # Replace with your AMI name filter
      register: amis

    - name: Debug AMIs found
      debug:
        var: amis.results

    - name: Create Spot Instance
      ec2_spot_instance_request:
        region: ap-south-1
        spot_price: "0.2"  # Specify your desired spot price
        count: 1
        state: present
        wait: yes
        launch_specifications:
          - image_id: "{{ item.id }}"
            instance_type: "{{ instance_type }}"
            key_name: "hyd.pem"  # Replace with your key pair
            security_groups: ["custom-sg"]  # Replace with your security group(s)
            subnet_id: "subnet-0280cef33d772aab0"  # Replace with your subnet ID
            monitoring: no
      loop: "{{ amis.results }}"
      loop_control:
        loop_var: item
      vars:
        instance_type:
          - r5d.xlarge
          - r5.xlarge
          - r6i.xlarge
