---
- name: Create Spot Instance with Available AMI
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check the ami ids
      amazon.aws.ec2_ami_info:
        owners: 429814750573
        filters:
          "tag:AMI name": v1.7
        region: ap-south-2
      register: amis

    - name: debug the output
      debug:
        msg: "{{ amis }}"
