---
- name: Create Spot Instance with Available AMI
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check the ami ids
      amazon.aws.ec2_ami_info:
        filters:
          "tag:Name": rhel
        region: ap-south-2
      register: amis

    - name: set the fact for ami
      ami_fact:
        ami_spot: "{{ amis.images[0].image_id }}"

    - name: debug the ami id
      debug:
        var: ami_spot
