---
- name: Create Spot Instance with Available AMI
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch Spot instance
      amazon.aws.ec2_spot_instance:
        region: ap-south-2
        launch_specification:
          image_id: ami-069c1f3ff4e7c7ca1
          key_name: hyd.pem
          instance_type: r6i.xlarge
          spot_price: "0.2"
          tags:
            - key: Name
              value: SpotInstance
            - key: Environment
              value: Production
