---
- name: Create Spot Instance with Available AMI
  hosts: localhost
  gather_facts: false
  vars:
    region1: ap-south-1
  tasks:
    - name: Check the ami ids
      amazon.aws.ec2_ami_info:
        filters:
          "tag:Name": rhel
        region: "{{ region1 }}"
      register: amis

    - name: set the fact for ami
      set_fact:
        ami_spot: "{{ amis.images[0].image_id }}"

    - name: debug the ami id
      debug:
        var: ami_spot

    - name: Launch Spot instance
      amazon.aws.ec2_spot_instance:
        region: "{{ region1 }}"
        launch_specification:
          image_id: "{{ ami_spot }}"
          key_name: mumbai
          instance_type: z1d.xlarge
          security_groups:
            - custom-sg
        spot_price: "0.2"
        tags:
          Name: RHEL
      register: aws_instance
