---
- name: Time
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Get the current date and time
      set_fact:
         current_datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"
         
    - name: get the current data and time
      debug:
        msg: "{{ current_datetime }}"
